;;; claude-sessions-org.el --- Claude Code sessions as Org data -*- lexical-binding: t -*-

;;; Commentary:

;; Writes every Claude Code session to a flat Org file so the agenda can query
;; it.  The file carries no structure of its own: one top-level heading per
;; session, all facts in properties.  Grouping, sorting and filtering happen at
;; query time in `org-agenda-custom-commands' and `ao/sessions-for-project'
;; (see org-config.el), which is what makes this less rigid than a pre-grouped
;; document.
;;
;; Entries deliberately carry no TODO keyword, and their only timestamp lives
;; in the :UPDATED: property rather than the body.  Together that makes them
;; invisible to `todo', `tags-todo' and `agenda' date views, so they cannot
;; leak into the existing agenda commands.  The cost is that stock recency
;; sorting does not work on them: `tsia-down' reads the TIMESTAMP_IA special
;; property, which is nil for a timestamp inside a property drawer, and is
;; day-granular besides.  `ao/agenda-cmp-updated' sorts on :UPDATED: instead.
;;
;; Project identity is the :PROJECT: property, never a tag, because `org-tag-re'
;; is "[[:alnum:]_@#%]+" and project names like my-project contain hyphens.
;;
;; The file is regenerated in full.  Hand edits are lost; status belongs in
;; `claude-sessions-status-file', set with `t' in the `claude-sessions' buffer.
;;
;; M-x claude-sessions-org-sync

;;; Code:

;; Loaded by explicit path: config modules live in `user-emacs-directory',
;; which is deliberately not on `load-path' (it would shadow real packages).
(require 'claude-sessions
         (expand-file-name "claude-sessions"
                           (file-name-directory (or load-file-name
                                                    buffer-file-name))))
(require 'map)
(require 'org)

(declare-function agent-shell-resume-session "agent-shell" (session-id))

(defgroup claude-sessions-org nil
  "Claude Code sessions exposed to Org."
  :group 'claude-sessions)

(defcustom claude-sessions-org-file
  (expand-file-name "~/org/claude-sessions.org")
  "Org file written by `claude-sessions-org-sync'.
Regenerated in full on every run."
  :type 'file
  :group 'claude-sessions-org)

;;;; Generation

(defun claude-sessions-org--timestamp (iso)
  "Return ISO 8601 string as an inactive Org timestamp."
  (condition-case nil
      (format-time-string "[%Y-%m-%d %a %H:%M]" (encode-time (iso8601-parse iso)))
    (error "")))

(defun claude-sessions-org--escape (text)
  "Return TEXT as a single line safe to place in a heading."
  (string-trim (replace-regexp-in-string "[ \t\n\r]+" " " (or text ""))))

(defun claude-sessions-org--insert-session (session)
  "Insert SESSION as a flat top-level entry."
  (pcase-let* ((`(,project . ,worktree)
                (claude-sessions--project-parts (or (map-elt session 'cwd) "")))
               (pr (map-elt session 'pr))
               (state (map-elt session 'status)))
    (insert "* " (claude-sessions-org--escape
                  (or (map-elt session 'title) "(untitled)"))
            "\n")
    (insert ":PROPERTIES:\n")
    (insert ":SESSION:  " (map-elt session 'sessionId) "\n")
    (insert ":PROJECT:  " project "\n")
    (when worktree
      (insert ":WORKTREE: " worktree "\n"))
    (insert ":CWD:      " (abbreviate-file-name (or (map-elt session 'cwd) "")) "\n")
    (insert ":UPDATED:  "
            (claude-sessions-org--timestamp (or (map-elt session 'updatedAt) "")) "\n")
    (when pr
      (insert ":PR:       " (format "%s#%s" (car pr) (cdr pr)) "\n"))
    (when state
      (insert ":STATE:    " state "\n"))
    (insert ":END:\n")
    (when-let* ((last (map-elt session 'summary)))
      (insert "Last: " last "\n"))
    (insert "\n")))

(defun claude-sessions-org--generate ()
  "Return the flat Org document as a string."
  (let ((statuses (claude-sessions--load-statuses))
        (pr-cache (claude-sessions--read-eld claude-sessions-pr-cache-file))
        (sessions nil))
    (dolist (session (append (claude-sessions--fetch) nil))
      (pcase-let* ((id (map-elt session 'sessionId))
                   (`(,prompt . ,pr) (claude-sessions--transcript-facts id))
                   ;; A status set by hand wins; GitHub only fills the gap.
                   (state (or (alist-get id statuses nil nil #'equal)
                              (claude-sessions--derived-status pr pr-cache))))
        (setf (alist-get 'status session) state)
        (setf (alist-get 'pr session) pr)
        (setf (alist-get 'summary session) (claude-sessions--summarize prompt))
        (push session sessions)))
    (with-temp-buffer
      (insert "#+TITLE: Claude Sessions\n")
      (insert "#+STARTUP: overview\n\n")
      (insert "# Generated by M-x claude-sessions-org-sync. Do not edit; edits are lost.\n")
      (insert "# Query with the S agenda command, or M-x ao/sessions-for-project.\n\n")
      (dolist (session (claude-sessions--sort-sessions (nreverse sessions)))
        (claude-sessions-org--insert-session session))
      (buffer-string))))

;;;###autoload
(defun claude-sessions-org-sync ()
  "Rewrite `claude-sessions-org-file' from the current sessions."
  (interactive)
  (let ((content (claude-sessions-org--generate)))
    (with-temp-file claude-sessions-org-file
      (insert content))
    ;; Keep an open buffer in step with what was just written.
    (when-let* ((buffer (get-file-buffer claude-sessions-org-file)))
      (with-current-buffer buffer
        (revert-buffer t t t))))
  (message "Wrote %s" (abbreviate-file-name claude-sessions-org-file)))

;;;; Resuming

(defun claude-sessions-org--session-cwd (id)
  "Return the directory session ID ran in, according to the adapter."
  (seq-some (lambda (session)
              (and (equal (map-elt session 'sessionId) id)
                   (map-elt session 'cwd)))
            (append (claude-sessions--fetch) nil)))

(defun claude-sessions-org-follow (id _arg)
  "Resume the session with ID in an `agent-shell'.
Uses the entry's :CWD: property when there is one, otherwise asks the
adapter where that session ran, so a tracker entry only has to carry
:SESSION:."
  (require 'agent-shell)
  (let ((cwd (or (and (derived-mode-p 'org-mode) (org-entry-get nil "CWD" t))
                 (claude-sessions-org--session-cwd id))))
    (unless cwd
      (user-error "Cannot tell which directory session %s ran in" id))
    (setq cwd (expand-file-name cwd))
    (unless (file-directory-p cwd)
      (user-error "Session directory is gone: %s" cwd))
    ;; `agent-shell' derives its cwd from the current buffer, which here is
    ;; the dashboard.  Point it at the session's own directory instead.
    (let ((default-directory (file-name-as-directory cwd)))
      (agent-shell-resume-session id))))

(org-link-set-parameters "claude-session" :follow #'claude-sessions-org-follow)

;;;###autoload
(defun claude-sessions-resume-at-point ()
  "Resume the session named by the :SESSION: property of the entry at point.
Accepts either a bare session id or a `claude-session' link as the
property value.  Works in the generated file, in an Org tracker entry,
and on an agenda line."
  (interactive)
  (let ((value (if (derived-mode-p 'org-agenda-mode)
                   (when-let* ((m (or (org-get-at-bol 'org-hd-marker)
                                      (org-get-at-bol 'org-marker))))
                     (org-entry-get m "SESSION" t))
                 (unless (derived-mode-p 'org-mode)
                   (user-error "Not in an Org or Agenda buffer"))
                 (org-entry-get nil "SESSION" t))))
    (unless value
      (user-error "No :SESSION: property on this entry"))
    (claude-sessions-org-follow
     (string-trim (if (string-match "claude-session:\\([^]]+\\)" value)
                      (match-string 1 value)
                    value))
     nil)))

(provide 'claude-sessions-org)

;;; claude-sessions-org.el ends here
